import com.squareup.leakcanary.AnalysisResult;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    private static Map<String, String> s_CMD_MAP = new HashMap<>();

    public static void main(String args[]) {
        if (args == null || args.length == 0) {
            help();
        }
        for (int i = 0; i < args.length; i = i + 2) {
            int j = i + 1;
            String value = "";
            if (s_CMD_MAP.size() > j) {
                value = args[j];
            }
            s_CMD_MAP.put(args[i], value);
        }
        List<AnalysisResult> results = null;
        LeakFinder leakFinder = null;
        if (s_CMD_MAP.containsKey("-t")) {
            leakFinder = new TargetActivityFinder();


        } else if (s_CMD_MAP.containsKey("-p")) {
            leakFinder = new DestroyedActivityLeakFinder();

        } else if (s_CMD_MAP.containsKey("-l")) {
            leakFinder = new LastHprofFinder();
        }
        leakFinder.prepare(s_CMD_MAP);
        results = leakFinder.find();
        if (results != null) {
            for (AnalysisResult result: results) {
                if (result != null) {
                    System.out.println(result.leakTrace);
                }
            }
        } else {
            System.out.println("results=null!");
        }
    }

    private static void help() {
        System.out.println("");
        System.out.println(">>>>>>>>Android Leak Finder<<<<<<<<<<");
        System.out.println("1. 找指定的类");
        System.out.println("   -t: 类名 ");
        System.out.println("   -f: hprof文件名");
        System.out.println("2. 自动查找包名下的Activity内存泄露");
        System.out.println("   -p: package name");
        System.out.println("3. analyzer last");
        System.out.println("   -l:last ");
        System.out.println("-h: 帮助");

    }


}
